[package]

name = "rocksdb"
description = "A Rust wrapper for Facebook's RocksDB embeddable database."
version = "0.4.5"
authors = ["Tyler Neely <t@jujit.su>", "David Greenberg <dsg123456789@gmail.com>"]
license = "Apache-2.0"
keywords = ["database", "embedded", "LSM-tree", "persistence"]
homepage = "https://github.com/paritytech/rust-rocksdb"
exclude = [
  ".gitignore",
  ".travis.yml",
  "deploy.sh",
  "test/**/*",
]

[features]
default=[]
valgrind=[]

[[test]]

name = "test"
path = "test/test.rs"

[dependencies]
libc = "0.2"
rocksdb-sys = { path = "rocksdb-sys", version = "0.3.0" }
local-encoding = "0.2.0"
